// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"
)

type Zone struct {
	ID        int32     `json:"id"`
	Createdat time.Time `json:"createdat"`
	Updatedat time.Time `json:"updatedat"`
	Zipcode   string    `json:"zipcode"`
	Zone      string    `json:"zone"`
	Temprange string    `json:"temprange"`
	Zonetitle string    `json:"zonetitle"`
	Year      int32     `json:"year"`
}
